### ISSUE TITLE
PCB default config without soldering

### ISSUE THREAD

**Issue by wassfila** [Informaticore/SuperPower#24]
In the current status and PR https://github.com/Informaticore/SuperPower/pull/23 the user of the PCB would have to solder the 1 cell jumper before he can use the board.
As 95% of users might be using a single cell, suggestion is to make it the default

- the pcb should be operational for 1 cell out of the box
- undersoldering an soldering 0 ohm and bridges should only be required if a different config 2 or more cells are required

**Comment by wassfila** [comment]
@MantaRayDeeJay I see two 0 ohm resistors, but is it possible to configure that only one of them is mounted by default ?
![image](https://user-images.githubusercontent.com/1510763/95677378-696ac580-0bc5-11eb-9fec-98982db99e45.png)

**Comment by MantaRayDeeJay** [comment]
![1_cell_default_settings](https://user-images.githubusercontent.com/20164048/95677367-535d0500-0bc5-11eb-920b-99ba12d339df.PNG)
Please see "Add default 1 cell setting"commit f8f52985ad4d266c95d80645a2a86bfdd51091e9

**Comment by wassfila** [comment]
I can't see such commit, maybe you did not push it yet ? when you mention a commit, you can copy and paste the hash number and github will create an automatic link, very convenient when we talk about commits

![image](https://user-images.githubusercontent.com/1510763/95677506-3e34a600-0bc6-11eb-80f7-307e14a2162c.png)

c1945163cbadd14c11eed62c1720836f3af2eb88

![image](https://user-images.githubusercontent.com/1510763/95677496-2bba6c80-0bc6-11eb-957a-38aef9547363.png)

**Comment by MantaRayDeeJay** [comment]
> 
> 
> @MantaRayDeeJay I see two 0 ohm resistors, but is it possible to configure that only one of them is mounted by default ?
> ![image](https://user-images.githubusercontent.com/1510763/95677378-696ac580-0bc5-11eb-9fec-98982db99e45.png)

![LTC4162-L - Cell Count Pin Mapping (recadré)](https://user-images.githubusercontent.com/20164048/95677469-0af21700-0bc6-11eb-99f8-5194e22a722e.png)
As you can see in the table, the 2 pins (CELLS0 and CELLS1) should be tied to INTVcc to select "1 CELL"

**Comment by wassfila** [comment]
issue already fixed with f8f52985ad4d266c95d80645a2a86bfdd51091e9
