### ISSUE TITLE
generate svg schematics for low cost variant

### ISSUE THREAD

**Issue by wassfila** [Informaticore/SuperPower#27]
The low cost variant might be our best seller to feed R&D of the Original (Premium) variant, so we might want to update the github action to generate the svg schematics separately.
@Informaticore I remember you mentioned that, but I can't see that in any branch, so we can use this as a reminder and close it simply if it was already done, then maybe link where.

current master 6b6abbf4b22ff191eef2cfc5b6933118083df25d
![image](https://user-images.githubusercontent.com/1510763/95679162-37f7f700-0bd1-11eb-9a93-50e56ad0f418.png)

**Comment by Informaticore** [comment]
this was done last week and can be found in the .generated folder

**Comment by wassfila** [comment]
@Informaticore is it now generated automatically on each action ? Or do we abandon the idea of automatic generation and update them manually when we need ? That would be ok for me, and if so, the ticket can stay closed.

**Comment by Informaticore** [comment]
back-pushing of the generated files is causing too much trouble. The action is still running on push (if *.sch files changed) and PRs so we can always find the files in the artifacts to push them manually.
