### ISSUE TITLE
document lowcost BOM

### ISSUE THREAD

**Issue by wassfila** [Informaticore/SuperPower#30]

**Comment by Tobi3566** [comment]
[SuperPower-uC-KiCad.txt](https://github.com/Informaticore/SuperPower/files/5366430/SuperPower-uC-KiCad.txt)

**Comment by Tobi3566** [comment]
[SuperPower-uC-KiCad (2).txt](https://github.com/Informaticore/SuperPower/files/5366446/SuperPower-uC-KiCad.2.txt)

**Comment by wassfila** [comment]
fixed with d1f85f1

**Comment by wassfila** [comment]
@Tobi3566 
https://superpower.readthedocs.io/en/latest/uc/low/overview.html
should be ok as a first draft
![image](https://user-images.githubusercontent.com/1510763/95774829-78cf3900-0cc1-11eb-8adb-de6c1ee1bbc1.png)
