### ISSUE TITLE
charge indicators measurement and user interface

### ISSUE THREAD

**Issue by wassfila** [Informaticore/SuperPower#44]
one comparator to be used to switch an LED on for status
- monitoring only when USB is connected
- when the current is below 25 mA it will turn the LED on
- to use a comparator (OpAmp) designed to be a comparator and not a generic OpAmp
- impact of sense resistor on the LTC4162 might affect it if its ground is lifted up, so might consider to measure from the top instead of from the ground.

## LED colors
- red LED to show the USB / Panel power
- blue led for charging 
be aware of high voltage that might not fit when using blue white and true green LEDs

![image](https://user-images.githubusercontent.com/1510763/97115649-10884a80-16f8-11eb-819e-28c87da1303c.png)

**Comment by wassfila** [comment]
@2010019970909 this might completely change the scope of this ticket, would you prefer to keep this one and we create a new one for the RGB LED ? Or is it ok to rename it like I did ?

**Comment by Vincent-Stragier** [comment]
@wassfila, maybe it's better to rename this ticket, "charge indicators (measurement and user interface)". IDK.

**Comment by wassfila** [comment]
@2010019970909 I did rename it like that. But actually the measurement part is going to fly away if we use the user LED and LTC readings.
Would you like to keep investigating the topic ? That's ok if you want maybe to keep it for future or other variants, or just if you want to finish something you started.

**Comment by wassfila** [comment]
fixed by #52 
the duplicated charge measure external to ltc won't be needed.
