### ISSUE TITLE
Can't load 3d model with FreeCad

### ISSUE THREAD

**Issue by wassfila** [Informaticore/SuperPower#73]
commit 43f4432fa330a83b1790b3b61581f4cfa3f51369

file -> Open -> "SuperPower-uC\original\SuperPower-uC-KiCad.kicad_pcb"

Error :
![image](https://user-images.githubusercontent.com/1510763/105753284-b8582300-5f48-11eb-9e5e-96132f45177e.png)

![image](https://user-images.githubusercontent.com/1510763/105753316-cb6af300-5f48-11eb-8145-a48f20548843.png)

![image](https://user-images.githubusercontent.com/1510763/105753323-d02fa700-5f48-11eb-9d3d-e9df0e37aea3.png)

![image](https://user-images.githubusercontent.com/1510763/105753337-d6258800-5f48-11eb-9cd2-2c260c7426d9.png)

**Comment by wassfila** [comment]
for the raspberry pi
commit 
https://github.com/sethkaz/SuperPower/commit/d3b12cf72331b07d9264cd0fdebfc268e367fad2

![image](https://user-images.githubusercontent.com/1510763/105755766-0f132c00-5f4c-11eb-8a82-f939597d1113.png)

**Comment by Vincent-Stragier** [comment]
I cannot reproduce the error, but I remember having it a few months ago.

![image](https://user-images.githubusercontent.com/28227183/105769723-894cac00-5f5e-11eb-8cca-a676fcf667d4.png)

I only had the info this time:

![image](https://user-images.githubusercontent.com/28227183/105769790-a71a1100-5f5e-11eb-997c-ae25668d46c7.png)

**Comment by MantaRayDeeJay** [comment]
@wassfila 

Try to use the "KiCAD StepUp" Module ToolBar to open the file.

![FreeCAD - KiCAD Board Step Export](https://user-images.githubusercontent.com/20164048/105772414-67edbf00-5f62-11eb-9103-0eeeb6a68383.png)

**Comment by MantaRayDeeJay** [comment]
@wassfila 

Which FreeCAD version are you using ?

**Comment by wassfila** [comment]
I have Freecad 0.18 but I can try the latest, I placed the StepUpMod on the Mod folder
![image](https://user-images.githubusercontent.com/1510763/105886866-3c72df00-600b-11eb-9a48-46ee3a8342eb.png)

And I only have this menu
![image](https://user-images.githubusercontent.com/1510763/105886915-4eed1880-600b-11eb-8988-8a0b530d6443.png)

**Comment by wassfila** [comment]
I think I was using a "fake" free version of Freecad I got from here
https://wiki.freecadweb.org/Installing_on_Windows

now I'm trying out this, that looks a bit more serious
https://www.freecadweb.org/downloads.php

Is that where you go it from ?

From the second link it's only the 0.18.4
![image](https://user-images.githubusercontent.com/1510763/105887337-e6526b80-600b-11eb-865a-f5af4018cf45.png)


OK, now I found this,
https://forum.freecadweb.org/viewtopic.php?t=41511

do I really need the developer build for the 3d pcb models to work ?

**Comment by MantaRayDeeJay** [comment]
@wassfila 

Try with the lastest v0.19 (Conda)
https://github.com/FreeCAD/FreeCAD/releases/tag/0.19_pre
 
Then use the Add-On Manager from the Tools Menu (last item) to download the "KiCAD StepUp" module.

![FC_v0 19_Add-On_Manager](https://user-images.githubusercontent.com/20164048/105889170-2b779d00-600e-11eb-8fe3-60592324b532.PNG)

**Comment by wassfila** [comment]
with developer version 0.19, still the same issue, 

![image](https://user-images.githubusercontent.com/1510763/105888955-e6ec0180-600d-11eb-9da7-b2de4dc138c6.png)

I must be doing something radically wrong.
Starting from all wiki telling about installing from add-on manager but not telling how

The addon managed of version 0.18 looks like this
![image](https://user-images.githubusercontent.com/1510763/105889101-1864cd00-600e-11eb-8068-bc7925d108ef.png)

**Comment by wassfila** [comment]
@MantaRayDeeJay thanks for your screenshot, that helped, only the version 0.19 show it and I was searching for S "StepUp" which it's in K "KicadStepUp" :)

**Comment by wassfila** [comment]
now version 0.19 with StepUp installed from the addon manager still the same issue lol

![image](https://user-images.githubusercontent.com/1510763/105889667-bbb5e200-600e-11eb-9574-77ea7cf9afbe.png)

This should have nothing to do with the Kicad installed version I guess

**Comment by MantaRayDeeJay** [comment]
@wassfila 

The Add-On Manager of the version v0.18.4 is not Up to date.
I saw that they want to release the v0.18.5 (with the add-on Manager Up to date)

But currently, the easiest way to download FreeCAD modules is from the download manager of the v0.19.xxx series.

**Comment by wassfila** [comment]
@MantaRayDeeJay are you running windows, cause I'm on windows
still v 0.19 look different
![image](https://user-images.githubusercontent.com/1510763/105890053-27984a80-600f-11eb-98f2-422b1f0d9084.png)

Can you screenshot your about menu ?

The toolbar is still different
![image](https://user-images.githubusercontent.com/1510763/105890122-3aab1a80-600f-11eb-90e8-3c0736830551.png)

**Comment by MantaRayDeeJay** [comment]
@wassfila 

I can see that on the last error screenshot, it loads 3D models from "Raspberry" folder.
It could explain the issue.

![105889667-bbb5e200-600e-11eb-9574-77ea7cf9afbe - with Arrow](https://user-images.githubusercontent.com/20164048/105890543-cd4bb980-600f-11eb-84ba-408786312002.png)

**Comment by Informaticore** [comment]
I am running 0.18 without the plug-in installed extra. Plain FreeCad and I just press open (folder on top) and open the pcb file. There is an error after loading the PCB but it is just because of something which can not be drawn but I see all things and the pcb is opened.

**Comment by MantaRayDeeJay** [comment]
![FC_v0 19-23546_about](https://user-images.githubusercontent.com/20164048/105890936-4814d480-6010-11eb-80f0-263a091647c7.PNG)

**Comment by wassfila** [comment]
I tried these two versions and they end up on a different About menu info than your screenshot, weird :
![image](https://user-images.githubusercontent.com/1510763/105891590-17816a80-6011-11eb-888f-70fef390928f.png)
![image](https://user-images.githubusercontent.com/1510763/105891624-223bff80-6011-11eb-842d-60f659c83700.png)

**Comment by MantaRayDeeJay** [comment]
I didn't have the lastest version (v0.19-23546)

**Comment by wassfila** [comment]
It's just that Kicad does not like me, might be related to the install path, I installed on D: and the plugins gets installed on the C , if it's that stupid, it would be hard to debug
![image](https://user-images.githubusercontent.com/1510763/105892606-6085ee80-6012-11eb-99ab-a5994e80dc28.png)

**Comment by MantaRayDeeJay** [comment]
"C:\Program Files\KiCad\share\kicad\modules\packages3d" is the good path (same as mine)

Could you check KiCAD Footprint paths ?

![KiCAD_3D_footprint_Path - with arrow](https://user-images.githubusercontent.com/20164048/105894120-39c8b780-6014-11eb-9454-b31468691831.PNG)

**Comment by wassfila** [comment]
It worked out, thanks a lot @MantaRayDeeJay it's thanks to your help, I realized that the StepUp Plugin was stupidly assuming that I have kicad installed on C:\ with a hardcoded path, I tried declaring the env var, even patched the hardcoded path in python, nothing helped, I had to copy all models on that C:\ path, then it worked.
It is so far fetched that today programs still do that, but then when I remember that both FreeCad and Kicad are free, I take it back, I used to hardcode paths myself when I was a kid lol

**Comment by wassfila** [comment]
![image](https://user-images.githubusercontent.com/1510763/106039455-6db9e080-60d9-11eb-929f-a1ad72f91224.png)
